In [1]:
import numpy as np

In [3]:
my_matrix=np.array([[2,4],[3,5]])

In [4]:
my_matrix[0]

array([2, 4])

In [5]:
my_matrix[1]

array([3, 5])

In [6]:
my_matrix[0][0]

np.int64(2)

In [7]:
my_matrix[0][1]

np.int64(4)

In [8]:
my_matrix[1][0]

np.int64(3)

In [10]:
my_matrix.sum()

np.int64(14)

In [12]:
numpy_matrix=np.array([[20,30],[40,50]])

In [13]:
numpy_matrix.sum()

np.int64(140)

In [14]:
#row * column

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.random.random((4,5))
# 4 saatır, 5 sutundan olusur. numpy random odulunden random metodunu kullandıgımız için iki kere yazdık

array([[0.90459391, 0.3618696 , 0.291304  , 0.39668702, 0.96201091],
       [0.77059672, 0.04788549, 0.05981113, 0.29385266, 0.61755863],
       [0.39132279, 0.27927794, 0.27306909, 0.96494077, 0.19617151],
       [0.61347404, 0.10173321, 0.17832963, 0.72939908, 0.69297913]])

In [24]:
first_array = np.array([[10,20],[30,40]])


In [25]:
second_array = np.array([[5,15],[25,35]])


In [26]:
first_array+second_array

array([[15, 35],
       [55, 75]])

In [27]:
first_array*3

array([[ 30,  60],
       [ 90, 120]])

In [28]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [29]:
third_array = np.array([[10],[20]])

In [30]:
first_array+third_array

array([[20, 30],
       [50, 60]])

In [34]:
#Broadcasting işlem,
# NumPy broadcasting: İki matrisin toplama/çarpma vb. işlemi için boyutlar aynı olmalı veya biri 1 olmalı;
# 1 olan boyut diğerine yayılır.
# burda 10,20 seklinde olan iki satır aynı elemanları yanına alarak genişler
# 10,10 ile 20,20 satıları olusur

#1.satır: [10, 20] + [10, 10] = [20, 30]
#2.satır: [30, 40] + [20, 20] = [50, 60]

In [35]:
third_array

array([[10],
       [20]])

In [37]:
third_array.shape


(2, 1)

In [6]:
import numpy as np
first_matrix = np.array([[10,20,30]])
second_matrix = np.array([[2,3],[2,3],[2,3]])




In [7]:
result_matrix=first_matrix.dot(second_matrix)

In [8]:
result_matrix

array([[120, 180]])

In [9]:
result_matrix.shape

(1, 2)