In [9]:
import numpy as np



In [10]:
new_array = np.random.randint(1,100,20)


In [11]:
new_array

array([77, 61, 61,  8, 93, 61, 13, 18, 52,  5, 19, 16, 15, 35, 48, 81, 28,
       69,  2,  1], dtype=int32)

In [12]:
new_array > 25


array([ True,  True,  True, False,  True,  True, False, False,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [13]:
new_array>25

array([ True,  True,  True, False,  True,  True, False, False,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [14]:
new_array[new_array>25]

array([77, 61, 61, 93, 61, 52, 35, 48, 81, 28, 69], dtype=int32)

In [15]:
#transpose & reshape


In [17]:
matrix_array=np.array([[10,20],[20,30],[30,40]])

In [18]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [19]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [21]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [23]:
random_array=np.random.random((6,1))

random_array


In [24]:
random_array.reshape(2,3)


array([[0.11547795, 0.33607978, 0.53402238],
       [0.1708556 , 0.40839776, 0.99809488]])

In [26]:
random_array.reshape(2,3)

array([[0.11547795, 0.33607978, 0.53402238],
       [0.1708556 , 0.40839776, 0.99809488]])

In [28]:
random_array.reshape(3,2)

array([[0.11547795, 0.33607978],
       [0.53402238, 0.1708556 ],
       [0.40839776, 0.99809488]])

In [29]:
# real life cases


In [31]:
data=np.array([10,12,13,15,18,20,105,120])

In [32]:
mean = np.mean(data)


In [33]:
mean

np.float64(39.125)

In [34]:
std=np.std(data)

In [35]:
std

np.float64(42.633430251388404)

In [36]:
z_scores=(data-mean)/std

In [37]:
z_scores

array([-0.68314935, -0.6362378 , -0.61278203, -0.56587049, -0.49550317,
       -0.44859163,  1.54514895,  1.89698552])

In [39]:
np.abs(z_scores)>1

array([False, False, False, False, False, False,  True,  True])

In [40]:
outliers=data[np.abs(z_scores)>1]

In [41]:

outliers


array([105, 120])

In [42]:
# math equations


In [43]:
# Solve 2x + 3y = 8 and 5x + 7y = 19


In [44]:
A=np.array([[2,3],[5,7]])

In [45]:
B=np.array([8,19])

In [47]:
solution=np.linalg.solve(A,B)

In [48]:
solution

array([1., 2.])

In [49]:
prices = np.array([100, 102, 105, 107, 110])


In [50]:
np.diff(prices)

array([2, 3, 2, 3])