In [1]:
import numpy as np

In [2]:
myList=[10,20,30,40]


In [3]:
type(myList)

list

In [5]:
np.array(myList)

array([10, 20, 30, 40])

In [8]:
numpy_array=np.array([10,20,30,40])

In [9]:
type(numpy_array)

numpy.ndarray

In [10]:
numpy_array.max()

np.int64(40)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
myList1=[1,2]


In [14]:
myList2=[2,3]

In [15]:
myList1+myList2

[1, 2, 2, 3]

In [17]:
numpy_array1=np.array(myList1)

In [19]:
numpy_array2=np.array(myList2)

In [21]:
numpy_array1+numpy_array2

array([3, 5])

In [22]:
numpy_array1-numpy_array2

array([-1, -1])

In [24]:
numpy_array1*numpy_array2

array([2, 6])

In [25]:
numpy_array1/numpy_array2

array([0.5       , 0.66666667])

In [27]:
numpy_array1 * 5


array([ 5, 10])

In [28]:
other_array = np.array([10,20,30,40,50])


In [29]:
other_array.min()


np.int64(10)

In [30]:
other_array.sum()


np.int64(150)

In [31]:
#indexing and arange

In [33]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
np_array=np.arange(0,10)

In [41]:
np_array[1]

np.int64(1)

In [43]:
np_array[-1]

np.int64(9)

In [44]:
np_array[1:4:]

array([1, 2, 3])

In [45]:
np_array[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
np_array[2:6:2]


array([2, 4])

In [47]:
np.random.randn(4)

array([ 0.34462213, -1.67986006, -0.11489501,  1.50336341])

In [49]:
np.random.randn(4,4)
# 4 satır 4 sutunluk random bir matris olusturur

array([[-0.92662417, -0.40717196, -0.61510464,  1.3272353 ],
       [ 1.37329952,  0.37106852,  1.08997267,  0.46860417],
       [-0.95061895, -0.8441862 ,  1.01654303,  0.41086584],
       [-0.02624914, -0.26646184,  1.07029378, -0.03965027]])

In [53]:
np.random.randint(1,300,25)

array([ 85,  21,  24, 253,  85,  72,  42, 129,  21, 151, 160, 195, 141,
       204, 207, 157,  73, 137, 108, 158,  54, 213, 180,  70, 206],
      dtype=int32)